"""add_users_auth

Revision ID: 810e009bbe22
Revises: 065f50984d90
Create Date: 2026-08-29 15:27:36.430895
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '810e009bbe22'
down_revision: Union[str, None] = '065f50984d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=240), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('department_scope', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
